from typing import Protocol


class DocumentStore(Protocol):
    def create_document(self, *args, **kwargs) -> dict: ...
    def get_document(self, document_id: str) -> dict | None: ...
    def list_documents(self) -> list[dict]: ...


class ChunkStore(Protocol):
    def create_chunks(self, chunks) -> None: ...
    def list_chunks(self, document_id: str) -> list[dict]: ...


class VectorIndex(Protocol):
    def upsert_vector(self, *args, **kwargs) -> None: ...
    def search(self, *args, **kwargs) -> list[dict]: ...


class KeywordIndex(Protocol):
    def search(self, query: str, top_k: int = 10, **kwargs) -> list[dict]: ...


class JobStore(Protocol):
    def create_job(self, job_type: str, payload: dict) -> dict: ...


class EmbeddingProvider(Protocol):
    def embed_texts(self, texts: list[str]) -> list[list[float]]: ...
    def embed_text(self, text: str) -> list[float]: ...


class LLMProvider(Protocol):
    def generate(self, prompt: str) -> str: ...


class RerankerProvider(Protocol):
    def score(self, query: str, candidate: dict) -> float: ...


class CitationVerifier(Protocol):
    def verify(self, claims_payload, sources: list[dict]) -> dict: ...
